language: ruby
cache: bundler
rvm:
- 2.1.5
- 2.1.0
- 2.0.0
- 1.9.3
notifications:
  email: false
  irc:
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
    channels:
    - ircs://irc.oftc.net#akerl
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true
