language: ruby
cache: bundler
rvm:
- 2.1.0
- 2.0.0
- 1.9.3
notifications:
  email: false
  irc:
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
    channels:
    - "irc.oftc.net#akerl"
    channel_key: sekrit
    on_success: always
    on_failure: always
